Added test coverage to ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,4 +44,22 @@ jobs:
       - uses: actions/checkout@v3
 
       - name: Test
-        run: go test -v ./...
+        run: |
+          go test -v ./... -coverprofile coverage.out -covermode count
+          go tool cover -func coverage.out
+
+      - name: Coverage
+        env:
+          TEST_COVERAGE_THRESHOLD: 75
+        run: |
+            echo "Quality Gate: checking test coverage is above threshold ..."
+            echo "Threshold             : $TEST_COVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
